name: ReleaseManagedSolution
on:
 push:
   branches: [ main ]
jobs:
  convert-to-managed:
    runs-on: windows-latest
    environment: 
      name: 'Build'
    steps:
    - uses: actions/checkout@v2
    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0.6.3
      with:
        solution-folder: solutions/ALMLab
        solution-file: out/solutions/ALMLab.zip
        solution-type: Unmanaged
    - name: Import unmanaged solution
      uses: microsoft/powerplatform-actions/import-solution@v0.6.3
      with:
        environment-url: 'https://orged306eb3.crm8.dynamics.com/'
        app-id: 'eea2237f-9cf4-43d5-8d31-7adec3760a63'
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: '3d90fb9c-95a2-4ed8-be40-9806698b91b9'
        solution-file: out/solutions/ALMLab.zip
        force-overwrite: true
        publish-changes: true
    - name: Export managed solution
      uses: microsoft/powerplatform-actions/export-solution@v0.6.3
      with:
        environment-url: 'https://orged306eb3.crm8.dynamics.com/'
        app-id: 'eea2237f-9cf4-43d5-8d31-7adec3760a63'
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: '3d90fb9c-95a2-4ed8-be40-9806698b91b9'
        solution-name: nkd
        managed: true
        solution-output-file: out/ship/ALMLab.zip
    - name: Upload to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: out/ship/ALMLab.zip
  release:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    environment: 
      name: 'Water'    
    steps:
    - uses: actions/checkout@v2
    - name: Fetch solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release/
    - name: Import solution
      uses: microsoft/powerplatform-actions/import-solution@v0.6.3
      with:
        environment-url: 'https://orged306eb3.crm8.dynamics.com/'
        app-id: 'eea2237f-9cf4-43d5-8d31-7adec3760a63'
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: '3d90fb9c-95a2-4ed8-be40-9806698b91b9'
        solution-file: out/release/ALMLab.zip
        force-overwrite: true
        publish-changes: true
